name: Run script to update Murasoli PDF daily

on:
  schedule:
    - cron: '30 2 * * *'  # Runs at 8 AM IST (2:30 AM UTC)
  workflow_dispatch:

jobs:
  update_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the script
      run: python main.py

    - name: Commit and push PDF
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add murasoli.pdf log.txt
        git commit -m "Update Murasoli PDF" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
